
import { useState, useCallback } from 'react';

// The correct base URL for npoint.io bins API
const BINS_API_URL = 'https://api.npoint.io/bins';

export const useSyncEngine = () => {
    const [isSyncing, setIsSyncing] = useState(false);
    const [lastSyncStatus, setLastSyncStatus] = useState<'success' | 'error' | 'idle'>('idle');
    const [error, setError] = useState<string | null>(null);

    // Creates a new bin and returns the hex ID generated by the service
    const createCloudBin = useCallback(async (fullData: any) => {
        setIsSyncing(true);
        setError(null);
        setLastSyncStatus('idle');
        try {
            const response = await fetch(BINS_API_URL, {
                method: 'POST',
                headers: { 
                    'Content-Type': 'application/json',
                    'Accept': 'application/json'
                },
                body: JSON.stringify({ ...fullData, lastUpdated: new Date().toISOString() }),
            });
            
            if (!response.ok) {
                const errText = await response.text();
                console.error('Server error response:', errText);
                throw new Error('Cloud creation failed at server');
            }
            
            const result = await response.json();
            // npoint returns the id inside the response
            const generatedId = result.id || result.binId;
            
            if (!generatedId) throw new Error('No ID returned from server');
            
            setLastSyncStatus('success');
            return generatedId as string; 
        } catch (err) {
            console.error('Vault Creation Error:', err);
            setError('අලුත් Vault එකක් සෑදීම අසාර්ථකයි. අන්තර්ජාලය පරීක්ෂා කරන්න.');
            setLastSyncStatus('error');
            return null;
        } finally {
            setIsSyncing(false);
        }
    }, []);

    // Updates an existing bin using PUT
    const uploadToCloud = useCallback(async (syncId: string, fullData: any) => {
        if (!syncId) return false;
        setIsSyncing(true);
        setError(null);
        try {
            const response = await fetch(`${BINS_API_URL}/${syncId}`, {
                method: 'PUT',
                headers: { 
                    'Content-Type': 'application/json',
                    'Accept': 'application/json'
                },
                body: JSON.stringify({ ...fullData, lastUpdated: new Date().toISOString() }),
            });
            
            if (!response.ok) throw new Error('Cloud update failed');
            
            setLastSyncStatus('success');
            return true;
        } catch (err) {
            console.error('Upload Error:', err);
            setError('Cloud Backup අසාර්ථකයි.');
            setLastSyncStatus('error');
            return false;
        } finally {
            setIsSyncing(false);
        }
    }, []);

    // Fetches data from an existing bin
    const fetchFromCloud = useCallback(async (syncId: string) => {
        if (!syncId) return null;
        setIsSyncing(true);
        setError(null);
        try {
            const response = await fetch(`${BINS_API_URL}/${syncId}`, {
                method: 'GET',
                headers: { 'Accept': 'application/json' }
            });
            
            if (!response.ok) {
                if (response.status === 404) return null;
                throw new Error('Cloud fetch failed');
            }
            
            const data = await response.json();
            setLastSyncStatus('success');
            return data;
        } catch (err) {
            console.error('Fetch Error:', err);
            setError('Cloud දත්ත ලබාගැනීම අසාර්ථකයි.');
            setLastSyncStatus('error');
            return null;
        } finally {
            setIsSyncing(false);
        }
    }, []);

    return { createCloudBin, uploadToCloud, fetchFromCloud, isSyncing, lastSyncStatus, error };
};
